swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
basePath: /api
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users/{userId}:
    get:
      operationId: findUserById
      description: Returns user object
      parameters:
        - name: userId
          in: path
          description: The ID of the user
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/User"
        default:
          description: Error
          schema:
            $ref: "#/definitions/Error"
definitions:
  UserBasicInfo:
    properties:
      name:
        type: string
        example: "Mr Bob Example"
      biography:
        type: string
        example: "I like bicycles"
      twitter:
        type: string
        example: "@bobexample"
      createdAt:
        type: string
        format: date-time
      lastSeenAt:
        type: string
        format: date-time

  User:
    properties:
      basicInfo:
        $ref: "#/definitions/UserBasicInfo"
      friends:
        type: array
        items:
          $ref: "#/definitions/UserBasicInfo"
        example:
          - name: James
            biography: Like Bond
            createdAt: 2017-11-12T22:27:35.278Z
            lastSeenAt: 2017-11-12T22:27:35.278Z
          - name: Dan
            biography: Yeah mayne
            twitter: "@danmayne"
            createdAt: 2017-11-12T22:27:35.278Z
            lastSeenAt: 2017-11-12T22:27:35.278Z

  Error:
    required:
      - message
    properties:
      message:
        type: string
        example: "An example error occurred"
